// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

public partial class AvailableSlots
{
    [Key]
    public int SlotID { get; set; }

    public int DoctorID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndTime { get; set; }

    public int MaxPatients { get; set; }

    public int CityID { get; set; }

    [ForeignKey("CityID")]
    [InverseProperty("AvailableSlots")]
    public virtual Cities City { get; set; }

    [ForeignKey("DoctorID")]
    [InverseProperty("AvailableSlots")]
    public virtual Users Doctor { get; set; }

    [InverseProperty("Slot")]
    public virtual ICollection<ScheduledAppointments> ScheduledAppointments { get; set; } = new List<ScheduledAppointments>();
}