// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

public partial class Cities
{
    [Key]
    public int CityID { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Country { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<AvailableSlots> AvailableSlots { get; set; } = new List<AvailableSlots>();
}