// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

[PrimaryKey("DoctorId", "PrivilegeLevel")]
public partial class DoctorPrivileges
{
    [Key]
    public int DoctorId { get; set; }

    [Key]
    public int PrivilegeLevel { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("DoctorPrivileges")]
    public virtual Users Doctor { get; set; }
}