// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

public partial class doctor_notes
{
    [Key]
    public int id { get; set; }

    public int questionnaireID { get; set; }

    [Required]
    [StringLength(100)]
    public string patient_purpose { get; set; }

    [Required]
    [StringLength(100)]
    public string family_history_melanoma { get; set; }

    [Required]
    [StringLength(100)]
    public string family_history_non_melanoma { get; set; }

    [Required]
    [StringLength(100)]
    public string personal_history_melanoma { get; set; }

    public int? melanoma_count { get; set; }

    [Required]
    [StringLength(100)]
    public string personal_history_carcinoma { get; set; }

    public int? bcc_count { get; set; }

    public int? scc_count { get; set; }

    [Required]
    public string other_carcinoma_description { get; set; }

    [Required]
    [StringLength(100)]
    public string skin_examination_today { get; set; }

    public bool dermoscopy_performed { get; set; }

    public int nevus_count { get; set; }

    public bool more_than_twenty_nevus_on_hands { get; set; }

    public bool atypical_nevi_presence { get; set; }

    public int? atypical_nevi_count { get; set; }

    public bool congenital_nevi_medium_size { get; set; }

    public string congenital_nevi_medium_location { get; set; }

    public bool congenital_nevi_giant_size { get; set; }

    public string congenital_nevi_giant_location { get; set; }

    public bool solar_lentigo { get; set; }

    public bool suspicious_melanoma { get; set; }

    public int? suspicious_melanoma_count { get; set; }

    [Required]
    [StringLength(100)]
    public string melanoma_detected_by { get; set; }

    public bool suspicious_bcc { get; set; }

    public int? suspicious_bcc_count { get; set; }

    [Required]
    [StringLength(100)]
    public string bcc_detected_by { get; set; }

    public bool suspicious_scc { get; set; }

    public int? suspicious_scc_count { get; set; }

    [Required]
    [StringLength(100)]
    public string scc_detected_by { get; set; }

    public bool actinic_keratosis { get; set; }

    [StringLength(5)]
    public string actinic_keratosis_number { get; set; }

    public int? actinic_keratosis_count { get; set; }

    [Required]
    [StringLength(100)]
    public string actinic_keratosis_detected_by { get; set; }

    public bool other_lesions { get; set; }

    public string other_lesions_description { get; set; }

    public bool hematological_decease { get; set; }

    public bool hiv_decease { get; set; }

    public bool other_immunosuppresion { get; set; }

    public string other_immunosuppresion_reason { get; set; }

    public bool other_deceases { get; set; }

    public string other_deceases_name { get; set; }

    public bool smoking { get; set; }

    public bool? ex_smoker { get; set; }

    [ForeignKey("questionnaireID")]
    [InverseProperty("doctor_notes")]
    public virtual Questionnaires questionnaire { get; set; }
}