// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using euromelanoma_api.Models.EuromelanomaContext;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace euromelanoma_api.Models.EuromelanomaContext
{
    public partial class EUROMELANOMAContext
    {
        private IEUROMELANOMAContextProcedures _procedures;

        public virtual IEUROMELANOMAContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new EUROMELANOMAContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IEUROMELANOMAContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class EUROMELANOMAContextProcedures : IEUROMELANOMAContextProcedures
    {
        private readonly EUROMELANOMAContext _context;

        public EUROMELANOMAContextProcedures(EUROMELANOMAContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetAvailableSlotsResult>> GetAvailableSlotsAsync(int? CityID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "CityID",
                    Value = CityID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetAvailableSlotsResult>("EXEC @returnValue = [dbo].[GetAvailableSlots] @CityID = @CityID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> SchedulePatientAppointmentAsync(int? PatientID, int? SlotID, string PhoneNumber, int? CityID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PatientID",
                    Value = PatientID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SlotID",
                    Value = SlotID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PhoneNumber",
                    Size = 30,
                    Value = PhoneNumber ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CityID",
                    Value = CityID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[SchedulePatientAppointment] @PatientID = @PatientID, @SlotID = @SlotID, @PhoneNumber = @PhoneNumber, @CityID = @CityID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
