// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

public partial class EUROMELANOMAContext : DbContext
{
    public EUROMELANOMAContext(DbContextOptions<EUROMELANOMAContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AvailableSlots> AvailableSlots { get; set; }

    public virtual DbSet<Cities> Cities { get; set; }

    public virtual DbSet<DoctorPrivileges> DoctorPrivileges { get; set; }

    public virtual DbSet<PasswordResetTokens> PasswordResetTokens { get; set; }

    public virtual DbSet<QuestionnaireDataPatient> QuestionnaireDataPatient { get; set; }

    public virtual DbSet<Questionnaires> Questionnaires { get; set; }

    public virtual DbSet<ScheduledAppointments> ScheduledAppointments { get; set; }

    public virtual DbSet<UserRequests> UserRequests { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<doctor_notes> doctor_notes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AvailableSlots>(entity =>
        {
            entity.HasKey(e => e.SlotID).HasName("PK__Availabl__0A124A4F297CF943");

            entity.HasOne(d => d.City).WithMany(p => p.AvailableSlots)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AvailableSlots_City");

            entity.HasOne(d => d.Doctor).WithMany(p => p.AvailableSlots)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DoctorSlot");
        });

        modelBuilder.Entity<Cities>(entity =>
        {
            entity.HasKey(e => e.CityID).HasName("PK__Cities__F2D21A9616B5020A");
        });

        modelBuilder.Entity<DoctorPrivileges>(entity =>
        {
            entity.HasKey(e => new { e.DoctorId, e.PrivilegeLevel }).HasName("PK__DoctorPr__51E18C994E130F9C");

            entity.HasOne(d => d.Doctor).WithMany(p => p.DoctorPrivileges).HasConstraintName("FK_DoctorPrivileges");
        });

        modelBuilder.Entity<PasswordResetTokens>(entity =>
        {
            entity.HasKey(e => e.TokenId).HasName("PK__Password__658FEEEA5EEC1943");

            entity.HasOne(d => d.User).WithMany(p => p.PasswordResetTokens)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PasswordR__UserI__4F7CD00D");
        });

        modelBuilder.Entity<QuestionnaireDataPatient>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Question__3213E83FC850EAEA");

            entity.HasOne(d => d.questionnaire).WithMany(p => p.QuestionnaireDataPatient)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Questionn__quest__5070F446");
        });

        modelBuilder.Entity<Questionnaires>(entity =>
        {
            entity.HasKey(e => e.QuestionnaireID).HasName("PK__Question__A56EF405727CAD15");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ScheduledAppointments>(entity =>
        {
            entity.HasKey(e => e.ScheduledAppointmentID).HasName("PK__Schedule__E40D08259F1818AA");

            entity.HasOne(d => d.Patient).WithMany(p => p.ScheduledAppointments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Patient");

            entity.HasOne(d => d.Slot).WithMany(p => p.ScheduledAppointments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Slot");
        });

        modelBuilder.Entity<UserRequests>(entity =>
        {
            entity.HasKey(e => e.UserID).HasName("PK__UserRequ__1788CCAC01948FB2");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UserID).HasName("PK__Users__1788CCACAD2734C9");
        });

        modelBuilder.Entity<doctor_notes>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__doctor_n__3213E83F7500B29B");

            entity.HasOne(d => d.questionnaire).WithMany(p => p.doctor_notes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__doctor_no__quest__4D94879B");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}