// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace euromelanoma_api.Models.EuromelanomaContext
{
    public partial class GetAvailableSlotsResult
    {
        public int SlotID { get; set; }
        public int DoctorID { get; set; }
        public int CityID { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public int? AvailableSlots { get; set; }
    }
}
