// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace euromelanoma_api.Models.EuromelanomaContext
{
    public partial class GetAvailableSlotsResult
    {
        public int SlotID { get; set; }
    }
}
