// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using euromelanoma_api.Models.EuromelanomaContext;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace euromelanoma_api.Models.EuromelanomaContext
{
    public partial interface IEUROMELANOMAContextProcedures
    {
        Task<List<GetAvailableSlotsResult>> GetAvailableSlotsAsync(int? cityID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SchedulePatientAppointmentResult>> SchedulePatientAppointmentAsync(int? patientID, string phoneNumber, int? cityID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
