// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

public partial class PasswordResetTokens
{
    [Key]
    public int TokenId { get; set; }

    public int UserId { get; set; }

    [Required]
    [StringLength(256)]
    public string Token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpiryDate { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("PasswordResetTokens")]
    public virtual Users User { get; set; }
}