// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

public partial class QuestionnaireDataPatient
{
    [Key]
    public int id { get; set; }

    public int questionnaireID { get; set; }

    [Required]
    [StringLength(10)]
    public string gender { get; set; }

    public int birth_year { get; set; }

    [Required]
    [StringLength(100)]
    public string birth_place { get; set; }

    [Required]
    [StringLength(100)]
    public string residence { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal weight { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal height { get; set; }

    [Required]
    [StringLength(50)]
    public string ethnicity { get; set; }

    [StringLength(100)]
    public string other_ethnicity { get; set; }

    [Required]
    [StringLength(50)]
    public string education_level { get; set; }

    [Required]
    [StringLength(50)]
    public string living_alone { get; set; }

    [Required]
    [StringLength(200)]
    public string reason_exam { get; set; }

    [Required]
    [StringLength(50)]
    public string full_body_check_done { get; set; }

    [Required]
    [StringLength(50)]
    public string hair_color { get; set; }

    [Required]
    [StringLength(100)]
    public string how_much_freckles { get; set; }

    [Required]
    [StringLength(100)]
    public string sun_reaction { get; set; }

    [Required]
    public string SunExposureFromAge0to12 { get; set; }

    [Required]
    public string SunExposureFromAge13to19 { get; set; }

    [Required]
    public string SunExposureFromAge20to40 { get; set; }

    [Required]
    public string SunExposureFromAge40to60 { get; set; }

    [Required]
    public string SunExposureFromAge60to80 { get; set; }

    [Required]
    public string SunExposureAfterAge80 { get; set; }

    [Required]
    [StringLength(100)]
    public string tanning_exposure { get; set; }

    [Required]
    [StringLength(50)]
    public string sunny_country_exposure { get; set; }

    public int? years_before_18 { get; set; }

    [StringLength(100)]
    public string location_before_18 { get; set; }

    public int? years_after_18 { get; set; }

    [StringLength(100)]
    public string location_after_18 { get; set; }

    [Required]
    [StringLength(50)]
    public string used_solarium { get; set; }

    public int? total_visits { get; set; }

    public int? first_visit_age { get; set; }

    public int? last_visit_age { get; set; }

    [Required]
    [StringLength(100)]
    public string had_childhood_burns { get; set; }

    [Required]
    [StringLength(100)]
    public string had_adolescence_burns { get; set; }

    [Required]
    [StringLength(100)]
    public string had_burns_between_20_40 { get; set; }

    [Required]
    [StringLength(100)]
    public string had_burns_between_40_60 { get; set; }

    [Required]
    [StringLength(100)]
    public string had_burns_between_60_80 { get; set; }

    [Required]
    [StringLength(100)]
    public string had_burns_after_80 { get; set; }

    [ForeignKey("questionnaireID")]
    [InverseProperty("QuestionnaireDataPatient")]
    public virtual Questionnaires questionnaire { get; set; }
}