// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

public partial class Questionnaires
{
    [Key]
    public int QuestionnaireID { get; set; }

    public int PatientID { get; set; }

    public int? DoctorID { get; set; }

    public int? Score { get; set; }

    public string BasicExamination { get; set; }

    public string Histopathology { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("DoctorID")]
    [InverseProperty("QuestionnairesDoctor")]
    public virtual Users Doctor { get; set; }

    [ForeignKey("PatientID")]
    [InverseProperty("QuestionnairesPatient")]
    public virtual Users Patient { get; set; }
}