// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

public partial class Questionnaires
{
    [Key]
    public int QuestionnaireID { get; set; }

    public int PatientID { get; set; }

    public int? DoctorID { get; set; }

    public int? Score { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    public bool Consent { get; set; }

    [ForeignKey("DoctorID")]
    [InverseProperty("QuestionnairesDoctor")]
    public virtual Users Doctor { get; set; }

    [ForeignKey("PatientID")]
    [InverseProperty("QuestionnairesPatient")]
    public virtual Users Patient { get; set; }

    [InverseProperty("questionnaire")]
    public virtual ICollection<QuestionnaireDataPatient> QuestionnaireDataPatient { get; set; } = new List<QuestionnaireDataPatient>();

    [InverseProperty("questionnaire")]
    public virtual ICollection<doctor_notes> doctor_notes { get; set; } = new List<doctor_notes>();
}