// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

public partial class ScheduledAppointments
{
    [Key]
    public int ScheduledAppointmentID { get; set; }

    public int SlotID { get; set; }

    public int PatientID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("PatientID")]
    [InverseProperty("ScheduledAppointments")]
    public virtual Users Patient { get; set; }

    [ForeignKey("SlotID")]
    [InverseProperty("ScheduledAppointments")]
    public virtual AvailableSlots Slot { get; set; }
}