// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace euromelanoma_api.Models.EuromelanomaContext
{
    public partial class SchedulePatientAppointmentResult
    {
        [StringLength(23)]
        public string Poruka { get; set; }
        public int Status { get; set; }
        public int id { get; set; }
    }
}
