// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

[Index("Email", Name = "UQ__UserRequ__A9D1053406EA3DD0", IsUnique = true)]
public partial class UserRequests
{
    [Key]
    public int UserID { get; set; }

    [Required]
    [StringLength(100)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(100)]
    public string LastName { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [MaxLength(500)]
    public byte[] PasswordHash { get; set; }

    [Required]
    [StringLength(50)]
    public string UserType { get; set; }

    [Required]
    [StringLength(100)]
    public string Username { get; set; }

    [StringLength(1)]
    public string Status { get; set; }
}