// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace euromelanoma_api.Models.EuromelanomaContext;

[Index("Email", Name = "UQ__Users__A9D10534DCF07C96", IsUnique = true)]
public partial class Users
{
    [Key]
    public int UserID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [MaxLength(500)]
    public byte[] PasswordHash { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string UserType { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Username { get; set; }

    [InverseProperty("Doctor")]
    public virtual ICollection<AvailableSlots> AvailableSlots { get; set; } = new List<AvailableSlots>();

    [InverseProperty("Doctor")]
    public virtual ICollection<DoctorPrivileges> DoctorPrivileges { get; set; } = new List<DoctorPrivileges>();

    [InverseProperty("Doctor")]
    public virtual ICollection<Questionnaires> QuestionnairesDoctor { get; set; } = new List<Questionnaires>();

    [InverseProperty("Patient")]
    public virtual ICollection<Questionnaires> QuestionnairesPatient { get; set; } = new List<Questionnaires>();

    [InverseProperty("Patient")]
    public virtual ICollection<ScheduledAppointments> ScheduledAppointments { get; set; } = new List<ScheduledAppointments>();
}